module;
#include <cstddef>
#include <cstdint>
#include <functional>

export module Type.Abstract_ethernet;

namespace Abstract {
    // Status codes returned by every fallible operation on Ethernet_device.
    export enum class Ethernet_status : uint8_t {
        Ok = 0,
        Not_initialized,      // called before initialize() succeeded
        Already_initialized,  // initialize() called twice without shutdown()
        Link_down,            // physical link is down
        Invalid_parameter,    // e.g. null pointer, zero/oversized length
        No_data_available,    // no frame queued to read right now
        Buffer_too_small,     // caller-supplied buffer can't hold the frame
        Timeout,              // hardware/driver-level timeout
        Hardware_error,       // peripheral/driver reported a fault
        Not_supported,        // operation not implemented on this backend
        Unknown
    };

    // Maximum standard (non-jumbo) Ethernet frame size, including the
    // 14-byte header and 4-byte FCS, without an 802.1Q VLAN tag.
    export inline constexpr size_t Max_ethernet_frame_size = 1518;

    // Invoked from within poll() when a complete frame has been received.
    // data/length are only valid for the duration of the call -- copy
    // anything you need to keep.
    export using Ethernet_frame_callback = std::function<void(const uint8_t *data, size_t length)>;

    // Abstract interface for initializing and using an Ethernet (Layer 2 /
    // MAC) interface. Implementations exist for:
    //   - Ethernet_samv71_mac : wraps the SAMV71's on-chip GMAC peripheral
    //   - Ethernet_windows    : wraps a real NIC on Windows via Npcap/WinPcap
    //
    // This is a raw-frame (Layer 2) interface: send_frame()/the receive
    // callback hand you complete Ethernet frames (destination MAC + source
    // MAC + EtherType + payload). There is no IP stack here.
    //
    // Reception is event-driven from the caller's point of view: register
    // a callback with set_receive_callback() and call poll() regularly
    // (e.g. once per main-loop iteration or from a dedicated
    // thread/task). poll() is what actually invokes your callback, and it
    // always does so from the calling context of poll() itself -- never
    // from an ISR (SAMV71) or a capture thread (Windows).
    export class Abstract_ethernet {
    public:
        virtual ~Abstract_ethernet() = default;

        // --- Lifecycle ------------------------------------------------
        // Brings the interface up using the given MAC address (6 bytes).
        // On Ethernet_samv71_mac this programs the GMAC's own MAC address
        // registers and starts the peripheral. On Ethernet_windows the
        // host NIC's MAC address usually can't be changed in software, so
        // the implementation treats mac_address as informational and
        // get_mac_address() returns the adapter's real, OS-reported
        // address.
        virtual Ethernet_status initialize(const uint8_t mac_address[6]) = 0;

        // Stops the interface and releases any hardware/OS resources.
        // Safe to call even if initialize() was never called or already
        // failed.
        virtual Ethernet_status shutdown() = 0;

        [[nodiscard]] virtual bool is_initialized() const = 0;

        // --- Link / identity --------------------------------------------
        [[nodiscard]] virtual bool is_link_up() const = 0;

        // Writes the 6-byte MAC address currently in use into
        // mac_address_out. Undefined contents if !is_initialized().
        virtual void get_mac_address(uint8_t mac_address_out[6]) const = 0;

        // --- Transmit -----------------------------------------------------
        // Sends one complete Ethernet frame (header through payload; do
        // not include the FCS -- it is generated by hardware/driver).
        // Blocks only long enough to hand the frame to hardware/OS, not
        // until it's off the wire.
        [[nodiscard]] virtual Ethernet_status send_frame(const uint8_t *data, size_t length) = 0;

        // --- Receive (event-driven) --------------------------------------
        // Registers the handler invoked by poll() for each received
        // frame. Pass nullptr to clear it. Not safe to call from within
        // the callback itself.
        virtual Ethernet_status set_receive_callback(Ethernet_frame_callback callback) = 0;

        // Drains any frames that have arrived since the last call and
        // invokes the registered callback once per frame, in the calling
        // context of poll(). Must be called regularly for reception to
        // make progress -- frames are queued internally between poll()
        // calls up to an implementation-defined limit, beyond which
        // newly arriving frames are dropped and accounted for via
        // get_last_error()/Hardware_error.
        virtual void poll() = 0;

        // Returns the status of the last failed operation on this object.
        [[nodiscard]] virtual Ethernet_status get_last_error() const = 0;
    };
} // Ethernet
